#!/usr/bin/env python3
"""Self-contained CI: genuinely earn C1-C5, then cold-repeat normal turtle combat.

No checked-in completion JSON or external scratch checkpoint is required.
--from-save is an optional local acceleration path and is explicitly reported.
"""
from __future__ import annotations
import argparse
import contextlib
import hashlib
import json
import os
from pathlib import Path
import shutil
import subprocess
import sys
import tempfile

from run_campaign_lifecycle_test import run_phase
from run_campaign_story_lifecycle_test import run_story
from run_headless import unexpected_errors

C2_PHASES = ("chapter1", "depart", "rune_partial", "runes", "rescue", "beacon99", "claim")
STORY_PHASES = ("c3_prepare", "c3_outer_partial", "c3_outer", "c4", "c5_partial", "c5_finish")
MARKER = "=== CAMPAIGN EARNED BUDGET LIFECYCLE PASS ==="


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("godot", nargs="?", default=os.environ.get("GODOT", "godot"))
    parser.add_argument("--from-save", type=Path,
                        help="Reuse a separately verified genuine C5 save for local acceleration")
    parser.add_argument("--log-dir", type=Path, help="Retain isolated source and combat artifacts")
    args = parser.parse_args()
    project = Path(__file__).resolve().parents[1]
    binary = shutil.which(args.godot)
    if binary is None:
        parser.error("Godot executable could not be resolved")
    godot = str(Path(binary).resolve())
    directory = (contextlib.nullcontext(str(args.log_dir.resolve())) if args.log_dir
                 else tempfile.TemporaryDirectory(prefix="hotw-earned-budget-"))
    with directory as value:
        root = Path(value)
        root.mkdir(parents=True, exist_ok=True)
        print("Earned-budget isolated artifacts: " + str(root), flush=True)
        env = os.environ.copy()
        for key, name in (("HOME", "home"), ("XDG_DATA_HOME", "data"),
                          ("XDG_CONFIG_HOME", "config"), ("XDG_CACHE_HOME", "cache")):
            folder = root / name
            folder.mkdir(exist_ok=True)
            env[key] = str(folder)
        env["GODOT_SILENCE_ROOT_WARNING"] = "1"
        version = subprocess.check_output([godot, "--version"], env=env, text=True).strip()
        if not version.startswith("4.7.stable"):
            print("FAIL: earned-budget acceptance requires Godot4.7 stable", flush=True)
            return 1
        save = root / "genuine-c5.json"
        expected = Path(str(save) + ".campaign_expected")
        env["HOTW_TEST_SAVE"] = str(save)
        if args.from_save:
            source = args.from_save.resolve()
            if not source.is_file():
                parser.error("--from-save must identify an existing genuine C5 checkpoint")
            if source != save:
                shutil.copyfile(source, save)
            print("Local acceleration: using supplied genuine C5 bytes; source-generation phases skipped", flush=True)
        else:
            save.unlink(missing_ok=True)
            expected.unlink(missing_ok=True)
            for phase in C2_PHASES:
                if not run_phase(godot, project, env, phase):
                    return 1
            for phase in STORY_PHASES:
                if not run_story(godot, project, env, phase):
                    return 1
            print("Genuine C1-C5 source generated by13 independent actual-story processes", flush=True)
        source_hash = hashlib.sha256(save.read_bytes()).hexdigest()
        print("EARNED_BUDGET_SOURCE " + json.dumps({"sha256": source_hash,
              "source_processes": 0 if args.from_save else 13,
              "inventory_note": "capacity fixture stock is discarded; only paid chapter bonus foods fund combat"}), flush=True)
        output = root / "combat"
        result = subprocess.run([sys.executable, str(project / "tests/run_campaign_earned_boss_test.py"),
                                 godot, str(save), "--output", str(output), "--repeats", "2"],
                                env=env, capture_output=True, text=True, timeout=1500)
        log = result.stdout + result.stderr
        (root / "combat-driver.log").write_text(log)
        print(log, end="", flush=True)
        if result.returncode != 0 or "=== CAMPAIGN EARNED BOSS COLD REPEATS PASS ===" not in log:
            return 1
        manifest = json.loads((output / "manifest.json").read_text())
        if len(manifest.get("results", [])) != 8 or not all(row.get("passed") for row in manifest["results"]):
            print("FAIL: missing or failed normal-budget lifecycle phase", flush=True)
            return 1
        for row in manifest["results"]:
            combat = row.get("EARNED_COMBAT_RESULT")
            if combat:
                print("EARNED_BUDGET_COMBAT " + json.dumps({"name": row["name"], **combat}), flush=True)
        # One more fresh process establishes terminal completion persisted,
        # independent of the ending process's in-memory quest/UI state.
        env["HOTW_TEST_SAVE"] = str(output / "normal-complete.json")
        cold = subprocess.run([godot, "--headless", "--path", str(project),
                               "res://tests/campaign_earned_boss_test.tscn", "--", "read_complete", "1"],
                              env=env, capture_output=True, text=True, timeout=180)
        cold_log = cold.stdout + cold.stderr
        (root / "cold-complete.log").write_text(cold_log)
        print(cold_log, end="", flush=True)
        if (cold.returncode != 0 or "=== CAMPAIGN EARNED BOSS PASS" not in cold_log
                or unexpected_errors("campaign_earned_boss", cold_log)):
            return 1
        print(MARKER, flush=True)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
