#!/usr/bin/env python3
"""Self-contained CI: genuinely earn C1-C5, then cold-repeat normal turtle combat.

No checked-in completion JSON or external scratch checkpoint is required.
--from-save is an optional local acceleration path and is explicitly reported.
"""
from __future__ import annotations
import argparse
import contextlib
import hashlib
import json
import os
from pathlib import Path
import shutil
import subprocess
import sys
import tempfile

from run_campaign_earned_boss_test import EarnedEvidence, isolated_runtime

C2_PHASES = ("chapter1", "depart", "rune_partial", "runes", "rescue", "beacon99", "claim")
STORY_PHASES = ("c3_prepare", "c3_outer_partial", "c3_outer", "c4", "c5_partial", "c5_finish")
MARKER = "=== CAMPAIGN EARNED BUDGET LIFECYCLE PASS ==="


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("godot", nargs="?", default=os.environ.get("GODOT", "godot"))
    parser.add_argument("--from-save", type=Path,
                        help="Reuse a separately verified genuine C5 save for local acceleration")
    parser.add_argument("--log-dir", type=Path, help="Retain isolated source and combat artifacts")
    args = parser.parse_args()
    project = Path(__file__).resolve().parents[1]
    binary = shutil.which(args.godot)
    if binary is None:
        parser.error("Godot executable could not be resolved")
    godot = str(Path(binary).resolve())
    directory = (contextlib.nullcontext(str(args.log_dir.resolve())) if args.log_dir
                 else tempfile.TemporaryDirectory(prefix="hotw-earned-budget-"))
    with directory as value:
        root = Path(value)
        root.mkdir(parents=True, exist_ok=True)
        print("Earned-budget isolated artifacts: " + str(root), flush=True)
        env = os.environ.copy()
        with isolated_runtime(env):
            return run_budget(args, parser, project, godot, root, env)


def run_budget(args, parser, project, godot, root, env) -> int:
    env["GODOT_SILENCE_ROOT_WARNING"] = "1"
    version = subprocess.check_output([godot, "--version"], env=env, text=True).strip()
    if not version.startswith("4.7.stable"):
        print("FAIL: earned-budget acceptance requires Godot4.7 stable", flush=True)
        return 1
    save = root / "genuine-c5.json"
    expected = Path(str(save) + ".campaign_expected")
    env["HOTW_TEST_SAVE"] = str(save)
    evidence = EarnedEvidence(root, godot, version, env, "campaign_earned_budget")

    def fail(reason: str) -> int:
        evidence.finish(False, reason)
        return 1

    if args.from_save:
        source = args.from_save.resolve()
        if not source.is_file():
            parser.error("--from-save must identify an existing genuine C5 checkpoint")
        if source != save:
            shutil.copyfile(source, save)
        evidence.manifest["supplied_source"] = evidence.snapshot(source, evidence.directory / "supplied-source.json")
        evidence.write()
        print("Local acceleration: using supplied genuine C5 bytes; source-generation phases skipped", flush=True)
    else:
        save.unlink(missing_ok=True)
        expected.unlink(missing_ok=True)
        for phases, scene, frames, timeout, marker, error_case in (
            (C2_PHASES, "campaign_acceptance_test", 160000, 300, "=== CAMPAIGN ACCEPTANCE PASS", "campaign_acceptance"),
            (STORY_PHASES, "campaign_story_acceptance_test", 200000, 420, "=== CAMPAIGN STORY ACCEPTANCE PASS", "campaign_story")):
            for phase in phases:
                command = [godot, "--headless", "--path", str(project),
                           "res://tests/" + scene + ".tscn", "--quit-after", str(frames), "--", phase]
                passed, log, _ = evidence.run("source-" + phase, save, command, timeout,
                                              marker, error_case, root / ("source-" + phase + ".log"))
                print(log, end="", flush=True)
                if not passed:
                    return fail("source-" + phase)
        print("Genuine C1-C5 source generated by13 independent actual-story processes", flush=True)
    evidence.manifest["genuine_c5_source"] = evidence.snapshot(save)
    evidence.write()
    source_hash = hashlib.sha256(save.read_bytes()).hexdigest()
    print("EARNED_BUDGET_SOURCE " + json.dumps({"sha256": source_hash,
          "source_processes": 0 if args.from_save else 13,
          "inventory_note": "capacity fixture stock is discarded; only paid chapter bonus foods fund combat"}), flush=True)
    output = root / "combat"
    command = [sys.executable, str(project / "tests/run_campaign_earned_boss_test.py"),
               godot, str(save), "--output", str(output), "--repeats", "2"]
    passed, log, _ = evidence.run("combat-driver", save, command, 1500,
        "=== CAMPAIGN EARNED BOSS COLD REPEATS PASS ===", None, root / "combat-driver.log", driver=True)
    print(log, end="", flush=True)
    if not passed:
        return fail("combat-driver")
    manifest = json.loads((output / "manifest.json").read_text())
    if len(manifest.get("results", [])) != 8 or not all(row.get("passed") for row in manifest["results"]):
        print("FAIL: missing or failed normal-budget lifecycle phase", flush=True)
        return fail("missing or failed normal-budget lifecycle phase")
    for row in manifest["results"]:
        combat = row.get("EARNED_COMBAT_RESULT")
        if combat:
            print("EARNED_BUDGET_COMBAT " + json.dumps({"name": row["name"], **combat}), flush=True)
    # One more fresh process establishes terminal completion persisted,
    # independent of the ending process's in-memory quest/UI state.
    command = [godot, "--headless", "--path", str(project),
               "res://tests/campaign_earned_boss_test.tscn", "--", "read_complete", "1"]
    passed, cold_log, _ = evidence.run("cold-complete", output / "normal-complete.json", command,
        180, "=== CAMPAIGN EARNED BOSS PASS", "campaign_earned_boss", root / "cold-complete.log")
    print(cold_log, end="", flush=True)
    if not passed:
        return fail("cold-complete")
    if "supplied_source" in evidence.manifest:
        evidence.discard_copy(evidence.manifest["supplied_source"])
    evidence.finish(True)
    print(MARKER, flush=True)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
